# Generated by Django 4.1.2 on 2023-07-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Traccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='vehiculos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motores_ha.categoria')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motores_ha.combustible')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motores_ha.condicion')),
                ('traccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motores_ha.traccion')),
                ('transmision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motores_ha.transmision')),
            ],
        ),
    ]
